services:
   ########################################## FRONTEND VUE (Dev) ##########################################
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:3000

  ########################################## BACKEND NEST (Dev) ###########################################
  nest:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: express-api-dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
